In [95]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [96]:
x = np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#2: Create y array with elements equal to 0.

In [97]:
y = np.zeros((3,3))
y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Q#3: Add x and y arrays.

In [98]:
x + y 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [99]:
x.shape , x.ndim , x.size , x.dtype

((3, 3), 2, 9, dtype('float64'))

## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [100]:
w = np.array([[11,12],[13,14],[15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [101]:
z = np.arange(1,4)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [102]:
newArray = np.vstack((w.T,z))
newArray ,


(array([[11, 13, 15],
        [12, 14, 16],
        [ 1,  2,  3]]),)

## Q#8: Print all elements of "newArray" using the loop.

In [103]:
for i in newArray:
    print(i)

[11 13 15]
[12 14 16]
[1 2 3]


## Q#9: Reverse the columns and rows of "newArray".

In [104]:
print(newArray)
print("-----------------------")
print(np.delete(newArray, 0 , axis=0))
print("-----------------------") 
print(np.delete(newArray,0, axis = 1))

[[11 13 15]
 [12 14 16]
 [ 1  2  3]]
-----------------------
[[12 14 16]
 [ 1  2  3]]
-----------------------
[[13 15]
 [14 16]
 [ 2  3]]


## Q#10: Decrement all elements of "newArray" with 1.

In [105]:
newArray - 1

array([[10, 12, 14],
       [11, 13, 15],
       [ 0,  1,  2]])

## Q#11: Find smallest and biggest values in "newArray".

In [106]:
np.max(newArray), np.min(newArray)

(16, 1)

## Q#12: Print the first row of "newArray" using indexing.

In [107]:
newArray[0]

array([11, 13, 15])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [108]:
print(newArray)
print(newArray[1,0])

[[11 13 15]
 [12 14 16]
 [ 1  2  3]]
12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [109]:
number = newArray[[2,0],[0,1]]
number # 1?

array([ 1, 13])

## Q#15: Change the shape of "newArray" to (9,1).

In [110]:
newestArray = np.full(3,333)
print(newestArray)
print(newArray.shape)

combineArray = np.vstack((newestArray,newArray))
print(newestArray)
print(combineArray.T)

newArray.reshape(1,9)



[333 333 333]
(3, 3)
[333 333 333]
[[333  11  12   1]
 [333  13  14   2]
 [333  15  16   3]]


array([[11, 13, 15, 12, 14, 16,  1,  2,  3]])

## Q#16: Change the shape of "newArray" to (3,2).

In [111]:
newShape = newArray[1:6] 
newShape.reshape(3,2)

array([[12, 14],
       [16,  1],
       [ 2,  3]])

# Well Done 🎉